<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.9.0</Version>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyName>MeetingFlow</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="Whisper.net" Version="1.9.1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\python-stt\meetingflow_stt.py" Link="python-stt\meetingflow_stt.py" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\python-stt\requirements.txt" Link="python-stt\requirements.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
